# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
bootloader: grub
efiBootLoader: "grub"

# ПРОСТЫЕ ПУТИ - теперь boot в отдельном subvolume
kernel: "/vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"

kernelLine: ", with Linux linux"
fallbackKernelLine: ", with Linux linux (fallback initramfs)"

efiBootloaderId: "EN-OS_0.8"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

timeout: "10"
installEFIFallback: true

kernelParameters: []
