# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Run mkinitcpio(8) with the given preset value

# Используем стандартное ядро linux
kernel: linux

# Безопасные настройки
be_unsafe: false
