# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0

modules-search: [ local ]

windowWidth: 1024
windowHeight: 768
windowMaximize: false
windowResizable: false

instances:
- id:       one
  module:   shellprocess
  config:   shellprocess-1.conf

- id:       two
  module:   shellprocess
  config:   shellprocess-2.conf

- id:       kernel
  module:   shellprocess
  config:   shellprocess-kernel.conf


- id:       btrfs-post
  module:   shellprocess
  config:   shellprocess-btrfs.conf

- id:       initramfs
  module:   shellprocess
  config:   shellprocess-initramfs.conf

- id:       kernel-install
  module:   shellprocess
  config:   shellprocess-kernel-install.conf

- id:       grub-btrfs
  module:   shellprocess
  config:   shellprocess-btrfs.conf

- id:       mount-fix
  module:   shellprocess
  config:   shellprocess-boot_mount_fix.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - packages
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - shellprocess@initramfs
  - initcpio
  - shellprocess@mount-fix
  - shellprocess@kernel-install
  - shellprocess@grub-btrfs
  - removeuser
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - shellprocess@btrfs-post
  - grubcfg
  - bootloader
  - shellprocess@two
  - preservefiles
  - umount
- show:
  - finished


branding: EN-OS

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
