[options]
HoldPkg     = pacman glibc dracut kernel-install-for-dracut eos-dracut

Architecture = auto

Color
ILoveCandy
VerbosePkgLists
ParallelDownloads = 5
DownloadUser = alpm
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[enrepo]
SigLevel = Optional TrustAll
Server = https://github.com/Endscape-Coding/EN-Repository/raw/main/repo/
