overwrite: true
prefer_grub_d: false
keep_distributor: false

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "saved"
    GRUB_DISABLE_SUBMENU: true
    GRUB_DISABLE_RECOVERY: true
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet splash"
    GRUB_DISABLE_OS_PROBER: false
    GRUB_GFXMODE: "1920x1080x32,1366x768x32,1024x768x32,auto"
    GRUB_GFXPAYLOAD_LINUX: "keep"
    GRUB_THEME: "/usr/share/grub/themes/en-os/theme.txt"
