# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.zsh_history
setopt HIST_IGNORE_ALL_DUPS

autoload -U colors && colors

set_light_purple_prompt() {
    local exit_code=$?

    LAVENDER='%F{183}'      # #d7afff
    LILAC='%F{189}'         # #d7d7ff
    PERIWINKLE='%F{147}'    # #afafff
    POWDER_BLUE='%F{153}'   # #afd7ff
    LIGHT_CYAN='%F{195}'    # #d7ffff
    RESET='%f%b'

    TOP_CORNER="╭─"
    BOTTOM_CORNER="╰─"
    LAMBDA="λ"

    local status_emoji="💠"
    [ $exit_code -ne 0 ] && status_emoji="⚡"

    local time_display=""
    if [ -n "${CMD_DURATION}" ] && [ "${CMD_DURATION}" -gt 1000 ]; then
        local seconds=$((CMD_DURATION / 1000))
        time_display="${POWDER_BLUE}took ${seconds}s${RESET}"
    fi

    PROMPT="${TOP_CORNER}${LAVENDER}%n${LILAC}@${PERIWINKLE}%m${RESET} in ${POWDER_BLUE}%~${RESET} ${status_emoji} ${time_display}
${BOTTOM_CORNER}${LIGHT_CYAN}${LAMBDA}${RESET} "
}

set_light_purple_prompt

autoload -U compinit
compinit

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

alias ll='ls -alh --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto'

fastfetch --logo /usr/logos/en-os.txt 2>/dev/null

setopt autocd            
setopt interactivecomments 
setopt notify             

setopt appendhistory    
setopt sharehistory
setopt extendedhistory

zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
