# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 999

script:
    - "-/usr/bin/pacman-key --init || true"
    - "-/usr/bin/pacman-key --populate || true"
