# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
dontChroot: false
timeout: 300

script:
    - |
      echo "Reinstall kernel"

      pacman -U --noconfirm /etc/linux/linux.pkg.tar.zst
      pacman -U --noconfirm /etc/linux/linux-headers.pkg.tar.zst

      rm -rf /etc/linux/ || true
      rm -rf /etc/linuz || true
      rm -rf /etc/core || true

      echo "Kernel reinstalled"
