# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Generate fstab with subvolumes for BTRFS
generateMounts: true

mountOptions:
    btrfs: "defaults,noatime,compress=zstd,ssd,subvol=@"
    ext4: "defaults"
    xfs: "defaults"
    vfat: "umask=0077"
    swap: "defaults"
