# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

remove:
  - archiso
  - memtest86+
  - mkinitcpio-archiso
