# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0

---

efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512M

defaultFileSystemType:  "btrfs"

availableFileSystems:  ["btrfs", "ext4", "ext3", "xfs", "f2fs", "vfat"]

btrfs:
    allowSubvolumes: true

    defaultSubvolumes:
        - path: "@"
          mountpoint: "/"

        - path: "@home"
          mountpoint: "/home"

        - path: "@log"
          mountpoint: "/var/log"

        - path: "@cache"
          mountpoint: "/var/cache"

        - path: "@boot"
          mountPoint: "/boot"

        - path: "@tmp"
          mountpoint: "/tmp"

        - path: "@snapshots"
          mountpoint: "/.snapshots"

    mountOptions: "defaults,noatime,compress=zstd,ssd"

    createOptions: "-f"

userSwapChoices:
    - none
    - small
    - suspend
    - file

defaultPartitionTableType: "gpt"

allowManualPartitioning: true

drawNestedPartitions: false
alwaysShowPartitionLabels: true

initialPartitioningChoice: none
initialSwapChoice: file

enableLuksAutomatedPartitioning: false

partitionLayouts:
    - name: "Btrfs с подтомами"
      description: "Рекомендуется для настольных систем"
      partitions:
        - filesystem: "vfat"
          size: 512M
          mountPoint: "/boot/efi"
          flags: [ "boot" ]
        - filesystem: "btrfs"
          size: 100%
          mountPoint: "/"
          btrfsSubvolumes:
            - path: "@"
              mountpoint: "/"
            - path: "@home"
              mountpoint: "/home"
            - path: "@log"
              mountpoint: "/var/log"
            - path: "@cache"
              mountpoint: "/var/cache"
            - path: "@tmp"
              mountpoint: "/tmp"
            - path: "@snapshots"
              mountpoint: "/.snapshots"

    - name: "Простой Btrfs"
      description: "Один раздел без подтомов"
      partitions:
        - filesystem: "vfat"
          size: 512M
          mountPoint: "/boot/efi"
          flags: [ "boot" ]
        - filesystem: "btrfs"
          size: 100%
          mountPoint: "/"

    - name: "Btrfs с отдельным home"
      description: "Home на отдельном подтоме"
      partitions:
        - filesystem: "vfat"
          size: 512M
          mountPoint: "/boot/efi"
          flags: [ "boot" ]
        - filesystem: "btrfs"
          size: 100%
          mountPoint: "/"
          btrfsSubvolumes:
            - path: "@"
              mountpoint: "/"
            - path: "@home"
              mountpoint: "/home"

lvm:
    enable: false

requiredStorage: 10.0
